# Generated by Django 4.0.3 on 2022-08-04 23:09

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_path)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_path)),
                ('bio', models.TextField(blank=True, max_length=1500, null=True)),
                ('screen_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=132)),
                ('address', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=15)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_links', models.JSONField()),
                ('profile_register', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
