# Generated by Django 4.1.5 on 2023-01-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
