# Generated by Django 4.0.3 on 2022-08-04 23:09

import codepen.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=100)),
                ('file_description', models.TextField()),
                ('file_name', models.CharField(max_length=100)),
                ('file_url', models.FileField(max_length=200, unique=True, upload_to=codepen.functions.upload_path)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
                ('uploaded_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
