# Generated by Django 4.2 on 2023-04-25 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pen.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_title', models.CharField(max_length=255)),
                ('pen_description', models.TextField(blank=True)),
                ('pen_slug', models.SlugField(max_length=100, unique=True)),
                ('pen_thumbnail', models.ImageField(blank=True, upload_to=pen.models.upload_path)),
                ('pen_status', models.CharField(choices=[('published', 'Published'), ('private', 'Private'), ('draft', 'Draft'), ('trash', 'Trash')], default='publish', max_length=32)),
                ('pen_platform', models.CharField(choices=[('html', 'HTML'), ('javascript', 'JavaScript (JSX)'), ('c', 'C, C++, C#'), ('php', 'PHP'), ('python', 'Python'), ('java', 'Java'), ('kotlin', 'Kotlin'), ('django', 'Django'), ('jinja', 'Jinja2'), ('go', 'Go'), ('groovy', 'Groovy'), ('R', 'R'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('vue', 'Vue.js'), ('xml', 'XML/HTML')], default='html', max_length=16)),
                ('pen_comments', models.BigIntegerField(blank=True)),
                ('pen_published', models.DateTimeField(auto_now_add=True)),
                ('pen_modified', models.DateTimeField(auto_now=True)),
                ('pen_love', models.ManyToManyField(blank=True, related_name='love', to=settings.AUTH_USER_MODEL)),
                ('pen_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('pen_view', models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PenSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, choices=[('3024-day', '3024 day'), ('3024-night', '3024 night'), ('abbott', 'Abbott'), ('abcdef', 'Abcdef'), ('ambiance-mobile', 'Ambiance mobile'), ('ambiance', 'Ambiance'), ('ayu-dark', 'Ayu dark'), ('ayu-mirage', 'Ayu mirage'), ('base16-dark', 'Base16 dark'), ('base16-light', 'Base16 light'), ('bespin', 'Bespin'), ('blackboard', 'Blackboard'), ('cobalt', 'Bobalt'), ('colorforth', 'Colorforth'), ('darcula', 'Darcula'), ('duotone-dark', 'Duotone dark'), ('duotone-light', 'Duotone light'), ('eclipse', 'Eclipse'), ('elegant', 'Elegant'), ('erlang-dark', 'Erlang dark'), ('gruvbox-dark', 'Qruvbox dark'), ('hopscotch', 'Hopscotch'), ('icecoder', 'Icecoder'), ('idea', 'Idea'), ('isotope', 'Isotope'), ('juejin', 'Juejin'), ('lesser-dark', 'Lesser dark'), ('liquibyte', 'Liquibyte'), ('lucario', 'Lucario'), ('material-darker', 'Material darker'), ('material-ocean', 'Material ocean'), ('material-palenight', 'Material palenight'), ('material', 'Material'), ('mbo', 'MBO'), ('mdn-like', 'MDN like'), ('midnight', 'Midnight'), ('monokai', 'Monokai'), ('moxer', 'Moxer'), ('neat', 'Neat'), ('neo', 'Neo'), ('night', 'Night'), ('nord', 'Nord'), ('oceanic-next', 'Oceanic next'), ('panda-syntax', 'Panda syntax'), ('paraiso-dark', 'Paraiso dark'), ('paraiso-light', 'Paraiso light'), ('pastel-on-dark', 'Pastel on dark'), ('railscasts', 'Railscasts'), ('rubyblue', 'Rubyblue'), ('seti', 'Seti'), ('shadowfox', 'Shadowfox'), ('solarized', 'Solarized'), ('ssms', 'SSMS'), ('the-matrix', 'The matrix'), ('twilight', 'twilight'), ('vibrant-ink', 'Vibrant ink'), ('xq-dark', 'XQ dark'), ('xq-light', 'XQ light'), ('yeti', 'Yeti'), ('yonce', 'Yonce'), ('zenburn', 'Zenburn')], max_length=100)),
                ('platform', models.CharField(choices=[('html', 'HTML'), ('javascript', 'JavaScript (JSX)'), ('c', 'C, C++, C#'), ('php', 'PHP'), ('python', 'Python'), ('java', 'Java'), ('kotlin', 'Kotlin'), ('django', 'Django'), ('jinja', 'Jinja2'), ('go', 'Go'), ('groovy', 'Groovy'), ('R', 'R'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('vue', 'Vue.js'), ('xml', 'XML/HTML')], max_length=100)),
                ('font', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('scss', models.TextField(blank=True, default='')),
                ('sass', models.TextField(blank=True, default='')),
                ('javascript', models.TextField(blank=True, default='')),
                ('cpp', models.TextField(blank=True, default='')),
                ('php', models.TextField(blank=True, default='')),
                ('python', models.TextField(blank=True, default='')),
                ('java', models.TextField(blank=True, default='')),
                ('go', models.TextField(blank=True, default='')),
                ('r', models.TextField(blank=True, default='')),
                ('ruby', models.TextField(blank=True, default='')),
                ('vue', models.TextField(blank=True, default='')),
                ('react', models.TextField(blank=True, default='')),
                ('xml', models.TextField(blank=True, default='')),
                ('pen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pen.pen')),
            ],
            options={
                'verbose_name': 'Pen data',
                'verbose_name_plural': 'Pen data',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_modified', models.DateTimeField(auto_now_add=True)),
                ('comment_published', models.DateTimeField(auto_now=True)),
                ('comment_parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pen.comment')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.pen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True, default='')),
                ('head', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.CharField(blank=True, default='', max_length=255)),
                ('css1', models.CharField(blank=True, default='', max_length=255)),
                ('css2', models.CharField(blank=True, default='', max_length=255)),
                ('css3', models.CharField(blank=True, default='', max_length=255)),
                ('css4', models.CharField(blank=True, default='', max_length=255)),
                ('css5', models.CharField(blank=True, default='', max_length=255)),
                ('css6', models.CharField(blank=True, default='', max_length=255)),
                ('css7', models.CharField(blank=True, default='', max_length=255)),
                ('css8', models.CharField(blank=True, default='', max_length=255)),
                ('css9', models.CharField(blank=True, default='', max_length=255)),
                ('css10', models.CharField(blank=True, default='', max_length=255)),
                ('css11', models.CharField(blank=True, default='', max_length=255)),
                ('css12', models.CharField(blank=True, default='', max_length=255)),
                ('css13', models.CharField(blank=True, default='', max_length=255)),
                ('css14', models.CharField(blank=True, default='', max_length=255)),
                ('css15', models.CharField(blank=True, default='', max_length=255)),
                ('css16', models.CharField(blank=True, default='', max_length=255)),
                ('css17', models.CharField(blank=True, default='', max_length=255)),
                ('css18', models.CharField(blank=True, default='', max_length=255)),
                ('css19', models.CharField(blank=True, default='', max_length=255)),
                ('css20', models.CharField(blank=True, default='', max_length=255)),
                ('js1', models.CharField(blank=True, default='', max_length=255)),
                ('js2', models.CharField(blank=True, default='', max_length=255)),
                ('js3', models.CharField(blank=True, default='', max_length=255)),
                ('js4', models.CharField(blank=True, default='', max_length=255)),
                ('js5', models.CharField(blank=True, default='', max_length=255)),
                ('js6', models.CharField(blank=True, default='', max_length=255)),
                ('js7', models.CharField(blank=True, default='', max_length=255)),
                ('js8', models.CharField(blank=True, default='', max_length=255)),
                ('js9', models.CharField(blank=True, default='', max_length=255)),
                ('js10', models.CharField(blank=True, default='', max_length=255)),
                ('js11', models.CharField(blank=True, default='', max_length=255)),
                ('js12', models.CharField(blank=True, default='', max_length=255)),
                ('js13', models.CharField(blank=True, default='', max_length=255)),
                ('js14', models.CharField(blank=True, default='', max_length=255)),
                ('js15', models.CharField(blank=True, default='', max_length=255)),
                ('js16', models.CharField(blank=True, default='', max_length=255)),
                ('js17', models.CharField(blank=True, default='', max_length=255)),
                ('js18', models.CharField(blank=True, default='', max_length=255)),
                ('js19', models.CharField(blank=True, default='', max_length=255)),
                ('js20', models.CharField(blank=True, default='', max_length=255)),
                ('pen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pen.pen')),
            ],
        ),
    ]
