# Generated by Django 4.0.3 on 2022-08-04 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pen', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendata',
            name='pen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pen.pen'),
        ),
        migrations.AddField(
            model_name='pen',
            name='pen_love',
            field=models.ManyToManyField(blank=True, related_name='love', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pen',
            name='pen_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='pen',
            name='pen_view',
            field=models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pen.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.pen'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='pen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pen.pen'),
        ),
    ]
