# Generated by Django 4.1.3 on 2022-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pen", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pen",
            name="pen_type",
            field=models.CharField(
                choices=[
                    ("html", "HTML"),
                    ("javascript", "JavaScript (JSX)"),
                    ("c", "C, C++, C#"),
                    ("php", "PHP"),
                    ("python", "Python"),
                    ("java", "Java"),
                    ("kotlin", "Kotlin"),
                    ("django", "Django"),
                    ("jinja", "Jinja2"),
                    ("go", "Go"),
                    ("groovy", "Groovy"),
                    ("R", "R"),
                    ("ruby", "Ruby"),
                    ("swift", "Swift"),
                    ("vue", "Vue.js"),
                    ("xml", "XML/HTML"),
                ],
                max_length=16,
            ),
        ),
    ]
