# Generated by Django 4.1.3 on 2022-11-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pen", "0003_alter_pen_pen_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pen",
            name="pen_comments",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
