# Generated by Django 4.2 on 2023-04-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='user',
            new_name='user_id',
        ),
    ]
