# Generated by Django 4.2 on 2023-04-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_rename_user_setting_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='user_id',
            new_name='user',
        ),
    ]
