# Generated by Django 4.2 on 2023-04-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_rename_user_id_setting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='auto_format',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='last_update',
        ),
    ]
