# Generated by Django 4.2 on 2023-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_remove_setting_auto_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='auto_format',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
