# Generated by Django 3.2.8 on 2022-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220905_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_verification_code',
            field=models.IntegerField(default=0),
        ),
    ]
