# Generated by Django 4.1.5 on 2023-01-07 13:34

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_follower_alter_user_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text='<ul class="helper-list"><li>The password length must be greater than or equal 8</li><li>The password must contain one or more uppercase and lowercase characters</li><li>The password must contain one or more special characters</li></ul>',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required 150 characters or fewer. Letters, digits and _ only.",
                max_length=100,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator],
            ),
        ),
    ]
